# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
rvm: 2.3.1
osx_image: xcode8
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/AFMActionSheet.xcworkspace -scheme AFMActionSheet-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,name=iPhone 7,OS=latest" | xcpretty -c
- pod lib lint --quick
